name: aksara_jawa_keyboard
description: A simple package for dispaying in-app keyboard on a devices like kiosk, flutter Linux, and Raspberry PI that dont have native keyboards.
version: 1.0.0
homepage: https://github.com/ziii08/aksara_jawa_keyboard.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: nyk Ngayogyan New
      fonts:
        - asset: assets/fonts/nyk Ngayogyan New Italic.ttf
    - family: nyk Ngayogyan Jejeg
      fonts:
        - asset: assets/fonts/nyk Ngayogyan Jejeg.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
